# Generated by Django 2.2.8 on 2020-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('transmission', models.IntegerField(choices=[(1, 'Механическая коробка передач'), (2, 'Автоматическая коробка передач'), (3, 'Робот')])),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
