# Generated by Django 2.2.6 on 2020-02-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200201_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(choices=[(1, 'Механическая коробка передач'), (2, 'Автоматическая коробка передач'), (3, 'Робот')], verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
